openapi: 3.2.0
info:
  title: Smartcat Job API
  version: v1
servers:
- url: /
tags:
- name: Job
paths:
  /api/integration/v3/job/verifiedForProject:
    get:
      tags:
      - Job
      summary: Fetch an array of jobs whose status is VERIFIED
      parameters:
      - name: projectId
        in: query
        description: Project ID
        required: true
        schema:
          type: string
          format: uuid
      - name: skip
        in: query
        description: 'Number of jobs to be skipped (default: 0)'
        schema:
          type: integer
          format: int32
          default: 0
      - name: limit
        in: query
        description: 'Number of jobs to fetch (default: 100)'
        schema:
          type: integer
          format: int32
          default: 100
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobModelV2Extended'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobModelV2Extended'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobModelV2Extended'
      operationId: getApiIntegrationV3JobVerifiedForProject
      x-operation-id-source: derived
  /api/integration/v3/job:
    get:
      tags:
      - Job
      summary: Fetch an array of jobs
      parameters:
      - name: projectId
        in: query
        description: Project ID
        required: true
        schema:
          type: string
          format: uuid
      - name: skip
        in: query
        description: 'Number of jobs to be skipped (default: 0)'
        schema:
          type: integer
          format: int32
          default: 0
      - name: limit
        in: query
        description: 'Number of jobs to fetch (default: 100)'
        schema:
          type: integer
          format: int32
          default: 100
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobModelV2Extended'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobModelV2Extended'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobModelV2Extended'
      operationId: getApiIntegrationV3Job
      x-operation-id-source: derived
components:
  schemas:
    JobStatus:
      enum:
      - inProgress
      - invitationPending
      - waitingForAssignment
      - waitingForPayment
      - verified
      - paidByCustomer
      - paidToFreelancer
      - markedAsPaid
      - invitationCanceled
      - invitationDeclined
      type: string
      description: Payment status
      format: int32
    JobModelV2Extended:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: Task ID
        invoiceNumber:
          type:
          - string
          - 'null'
          description: Bank account number
        supplierEmail:
          type:
          - string
          - 'null'
          description: Vendor email address
        supplierName:
          type:
          - string
          - 'null'
          description: Vendor name
        supplierType:
          $ref: '#/components/schemas/SupplierType'
        serviceType:
          type:
          - string
          - 'null'
          description: Service type
        jobDescription:
          type:
          - string
          - 'null'
          description: 'Description: the name of a document or project'
        unitsType:
          type:
          - string
          - 'null'
          description: Job unit type
        unitsAmount:
          type: number
          description: Job unit count
          format: double
        customerPricePerUnit:
          type: number
          description: Job unit price
          format: double
        executivePricePerUnit:
          type: number
          description: Job unit price without commission
          format: double
        customerCurrency:
          type:
          - string
          - 'null'
          description: Price and cost currency
        executiveCurrency:
          type:
          - string
          - 'null'
          description: Linguist's price and cost currency
        customerCost:
          type: number
          description: Total job cost
          format: double
        executiveCost:
          type: number
          description: Total job cost without commission
          format: double
        externalNumber:
          type:
          - string
          - 'null'
          description: External payment ID
        supplierId:
          type:
          - string
          - 'null'
          description: Supplier ID
          format: uuid
        status:
          $ref: '#/components/schemas/JobStatus'
        projectId:
          type:
          - string
          - 'null'
          description: Project ID
          format: uuid
        deadline:
          type:
          - string
          - 'null'
          description: Project deadline
          format: date-time
        sourceLanguage:
          type:
          - integer
          - 'null'
          description: Source language
          format: int32
        targetLanguage:
          type:
          - integer
          - 'null'
          description: Target language
          format: int32
        isPaidExternally:
          type: boolean
          description: Paid externally
        documentId:
          type:
          - string
          - 'null'
          description: Document ID
        stageId:
          type:
          - string
          - 'null'
          description: Workflow stage ID
        verifiedDate:
          type:
          - string
          - 'null'
          description: The date the job status was set to VERIFIED.
          format: date-time
      additionalProperties: false
      description: Payment model
    SupplierType:
      enum:
      - freelancer
      - company
      type: string
      description: Supplier type
      format: int32
