openapi: 3.2.0
info:
  title: Smartcat Client API
  version: v1
servers:
- url: /
tags:
- name: Client
paths:
  /api/integration/v1/client/create:
    post:
      tags:
      - Client
      summary: Create a new client with the specified name and return their ID Simply return…
      requestBody:
        description: Client name
        content:
          application/json-patch+json:
            schema:
              type: string
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                type: string
                format: uuid
            application/json:
              schema:
                type: string
                format: uuid
            text/json:
              schema:
                type: string
                format: uuid
      operationId: postApiIntegrationV1ClientCreate
      x-operation-id-source: derived
  /api/integration/v1/client/{clientId}/set:
    put:
      tags:
      - Client
      summary: Apply the specified net rate to the specified client
      parameters:
      - name: clientId
        in: path
        description: Client ID
        required: true
        schema:
          type: string
          format: uuid
      - name: netRateId
        in: query
        description: Net rate ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientModel'
        '404':
          description: The specified client or net rate were not found in the current account
      operationId: putApiIntegrationV1ClientByClientIdSet
      x-operation-id-source: derived
  /api/integration/v1/client/{clientId}/contact:
    put:
      tags:
      - Client
      summary: Sets contact details for the specified client
      parameters:
      - name: clientId
        in: path
        description: Client ID
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: Contact details
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ContactModel'
          application/json:
            schema:
              $ref: '#/components/schemas/ContactModel'
          text/json:
            schema:
              $ref: '#/components/schemas/ContactModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ContactModel'
        required: true
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientModel'
        '400':
          description: Contact details are incorrect
        '404':
          description: The specified client not found
      operationId: putApiIntegrationV1ClientByClientIdContact
      x-operation-id-source: derived
  /api/integration/v2/client/{clientId}:
    put:
      tags:
      - Client
      summary: Update client details
      parameters:
      - name: clientId
        in: path
        description: Client ID
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        description: Client update model
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateClientModel'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClientModel'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateClientModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateClientModel'
        required: true
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientModelV2'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientModelV2'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientModelV2'
        '400':
          description: 'Returns if:

            - contact details are invalid

            - the provided manager ID is invalid'
        '404':
          description: The specified client not found
      operationId: putApiIntegrationV2ClientByClientId
      x-operation-id-source: derived
    get:
      tags:
      - Client
      summary: Fetch the client account information
      parameters:
      - name: clientId
        in: path
        description: Client ID
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientModelV2'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientModelV2'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientModelV2'
        '404':
          description: The specified client was not found in the current account
      operationId: getApiIntegrationV2ClientByClientId
      x-operation-id-source: derived
  /api/integration/v1/client/{clientId}:
    get:
      tags:
      - Client
      summary: Fetch the client account information
      parameters:
      - name: clientId
        in: path
        description: Client ID
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ClientModel'
            application/json:
              schema:
                $ref: '#/components/schemas/ClientModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ClientModel'
        '404':
          description: The specified client was not found in the current account
      operationId: getApiIntegrationV1ClientByClientId
      x-operation-id-source: derived
components:
  schemas:
    ContactModel:
      type: object
      properties:
        email:
          type:
          - string
          - 'null'
          description: Client email
        fullName:
          type:
          - string
          - 'null'
          description: Client name
        phoneNumber:
          type:
          - string
          - 'null'
          description: Contact phone number
        position:
          type:
          - string
          - 'null'
          description: Position
        comment:
          type:
          - string
          - 'null'
          description: Commentary
      additionalProperties: false
      description: Contact information model
    ClientModelV2:
      type: object
      properties:
        id:
          type: string
          description: Client ID
          format: uuid
        name:
          type:
          - string
          - 'null'
          description: Name
        netRate:
          $ref: '#/components/schemas/NetRateModel'
        mainContact:
          $ref: '#/components/schemas/ContactModel'
        additionalContacts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ContactModel'
          description: Additional contacts
        vat:
          type:
          - string
          - 'null'
          description: VAT
        countryCode:
          type:
          - string
          - 'null'
          description: Country code
        comment:
          type:
          - string
          - 'null'
          description: Commentary
        website:
          type:
          - string
          - 'null'
          description: Website
        industryId:
          type:
          - string
          - 'null'
          description: Specialization
        legalName:
          type:
          - string
          - 'null'
          description: Legal name
        address:
          type:
          - string
          - 'null'
          description: Address
        languageId:
          type:
          - integer
          - 'null'
          description: Language
          format: int32
        vendorManager:
          type:
          - string
          - 'null'
          description: Manager
        customFields:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
          description: Custom fields
      additionalProperties: false
      description: Client model
    NetRateModel:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          description: Net rate ID
        name:
          type:
          - string
          - 'null'
          description: Net rate name
        newWordsRate:
          type: number
          description: New words rate
          format: double
        repetitionsRate:
          type: number
          description: Repetitions rate
          format: double
        tmMatchRates:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/NetRateModel_TMRangeRateModel'
          description: TM matches rate
      additionalProperties: false
      description: Rate discounts model
    UpdateClientModel:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: Name
        netRateId:
          type:
          - string
          - 'null'
          description: ID of discount rates applicable to client
        mainContact:
          $ref: '#/components/schemas/ContactModel'
        additionalContacts:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/ContactModel'
          description: Additional contacts
        vat:
          type:
          - string
          - 'null'
          description: VAT
        countryCode:
          type:
          - string
          - 'null'
          description: Country code
        comment:
          type:
          - string
          - 'null'
          description: Commentary
        website:
          type:
          - string
          - 'null'
          description: Website
        industryId:
          type:
          - string
          - 'null'
          description: Entry ID in the client specializations list
        legalName:
          type:
          - string
          - 'null'
          description: Legal name
        address:
          type:
          - string
          - 'null'
          description: Address
        languageId:
          type:
          - integer
          - 'null'
          description: Language
          format: int32
        vendorManager:
          type:
          - string
          - 'null'
          description: Manager
        customFieldValues:
          type:
          - object
          - 'null'
          additionalProperties:
            type:
            - string
            - 'null'
          description: Customized field values
      additionalProperties: false
      description: Client update model
    ClientModel:
      type: object
      properties:
        id:
          type: string
          description: Client ID
          format: uuid
        name:
          type:
          - string
          - 'null'
          description: Name
        netRate:
          $ref: '#/components/schemas/NetRateModel'
        contact:
          $ref: '#/components/schemas/ContactModel'
      additionalProperties: false
      description: Client model
    NetRateModel_TMRangeRateModel:
      type: object
      properties:
        fromQuality:
          type: integer
          description: The lowest value in a TM match quality range
          format: int32
        toQuality:
          type: integer
          description: The highest value in a TM match quality range
          format: int32
        value:
          type: number
          description: TM range rate model
          format: double
      additionalProperties: false
      description: TM matches rate model
