openapi: 3.2.0
info:
  title: Smartcat Template API
  version: v1
servers:
- url: /
tags:
- name: Template
paths:
  /api/integration/v1/template:
    get:
      tags:
      - Template
      summary: Get all templates available in the workspace
      responses:
        '200':
          description: List of templates
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TemplateListModel'
            application/json:
              schema:
                $ref: '#/components/schemas/TemplateListModel'
            text/json:
              schema:
                $ref: '#/components/schemas/TemplateListModel'
      operationId: getApiIntegrationV1Template
      x-operation-id-source: derived
components:
  schemas:
    TemplateInfoModel:
      type: object
      properties:
        id:
          type: string
          description: Template ID
          format: uuid
        name:
          type:
          - string
          - 'null'
          description: Template name
      additionalProperties: false
      description: Template information model
    TemplateListModel:
      type: object
      properties:
        templates:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/TemplateInfoModel'
          description: List of templates
      additionalProperties: false
      description: Template list model
