openapi: 3.2.0
info:
  title: Smartcat User Deletion Requests API
  version: v1
servers:
- url: /
tags:
- name: UserDeletionRequests
paths:
  /api/integration/v1/user-deletion-requests:
    post:
      tags:
      - UserDeletionRequests
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
      summary: Create api integration user deletion requests
      x-summary-source: derived
      operationId: postApiIntegrationV1UserDeletionRequests
      x-operation-id-source: derived
  /api/integration/v1/user-deletion-requests/confirm:
    post:
      tags:
      - UserDeletionRequests
      parameters:
      - name: token
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create api integration user deletion requests confirm
      x-summary-source: derived
      operationId: postApiIntegrationV1UserDeletionRequestsConfirm
      x-operation-id-source: derived
