openapi: 3.2.0
info:
  title: Smartcat Account API
  version: v1
servers:
- url: /
tags:
- name: Account
paths:
  /api/integration/v1/account:
    get:
      tags:
      - Account
      summary: Fetch the account details
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AccountModel'
            application/json:
              schema:
                $ref: '#/components/schemas/AccountModel'
            text/json:
              schema:
                $ref: '#/components/schemas/AccountModel'
        '404':
          description: Unable to find an account connected to the integration API
      operationId: getApiIntegrationV1Account
      x-operation-id-source: derived
  /api/integration/v1/account/mtengines:
    get:
      tags:
      - Account
      summary: Fetch the list of MT services available for the account
      responses:
        '200':
          description: Request has been successfully completed
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MTEngineModel'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MTEngineModel'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MTEngineModel'
      operationId: getApiIntegrationV1AccountMtengines
      x-operation-id-source: derived
components:
  schemas:
    EndCustomerValue:
      enum:
      - lowValue
      - enterprise
      - sMB
      - corporate
      - university
      - government
      - strategic
      - smallBusiness
      - midmarket
      - anonymous
      type: string
      format: int32
    MTEngineModel:
      type: object
      properties:
        id:
          type: string
          description: ID
          format: uuid
        name:
          type:
          - string
          - 'null'
          description: MT engine name
      additionalProperties: false
      description: MT (Machine Translation) engine model
    AccountModel:
      type: object
      properties:
        id:
          type: string
          description: ID
          format: uuid
        name:
          type:
          - string
          - 'null'
          description: Name
        description:
          type:
          - string
          - 'null'
          description: Description
        isPersonal:
          type: boolean
          description: Specifies whether it is the user's personal account
        type:
          type:
          - string
          - 'null'
          description: Account type
        endCustomerValue:
          $ref: '#/components/schemas/EndCustomerValue'
        dateCreated:
          type: string
          description: Creation date
          format: date-time
        interInstallationAccountId:
          type: string
          description: Account ID for interacting with resources shared between installations
          format: uuid
        createdByUserId:
          type:
          - string
          - 'null'
          description: User ID who created the account
        organizationId:
          type:
          - string
          - 'null'
          description: Organization ID to which the account belongs
          format: uuid
        isDisabled:
          type: boolean
          description: Attribute of "disabled" personal account
      additionalProperties: false
      description: Account information for external systems
